/**
 * Copyright 2025 Beijing Volcano Engine Technology Co., Ltd. All Rights Reserved.
 * SPDX-license-identifier: BSD-3-Clause
 */

import Conversation from './Conversation';
import ToolBar from './ToolBar';
import AudioController from './AudioController';
import utils from '@/utils/utils';
import style from './index.module.less';

function Room() {
  return (
    <div className={`${style.wrapper} ${utils.isMobile() ? style.mobile : ''}`}>
      <Conversation className={style.conversation} />
      <ToolBar className={style.toolBar} />
      <AudioController className={style.controller} />
      <div className={style.declare}>
        AI-generated content is generated by llm, which cannot fully guarantee authenticity.
      </div>
    </div>
  );
}

export default Room;
